[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/juaryR/treinamento-h2ai/blob/initial/buscasSemInforma%C3%A7%C3%A3o.ipynb)

# O Problema
Sliding Puzzle - Bloco Deslizante

In [ ]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)

# Resolver o quebra-cabeças usando Buscas

In [159]:
import numpy as np

class Board:

    def __init__(self, state, parent=None, operator=None, depth=0):
        self.parent = parent
        self.state = np.array(state)
        self.operator = operator
        self.depth = depth
        self.zero = self.index_vazio()

    def objetivo(self):
        return np.array_equal(self.state, np.arange(9))

    def index_vazio(self):
         return a.tolist().index(0)
           
    def trocaValores(self, i, j):
        new_state = np.array(self.state)
        new_state[i], new_state[j] = new_state[j], new_state[i]
        return new_state

    def praCima(self):
        if self.zero > 2:
            return Board(self.trocaValores(self.zero, self.zero - 3), self, 'praCima', self.depth + 1)
        else:
            return None

    def praBaixo(self):
        if self.zero < 6:
            return Board(self.trocaValores(self.zero, self.zero + 3), self, 'praBaixo', self.depth + 1)
        else:
            return None

    def esquerda(self):
        if self.zero % 3 != 0:
            return Board(self.trocaValores(self.zero, self.zero - 1), self, 'esquerda', self.depth + 1)
        else:
            return None

    def direita(self):
        if (self.zero + 1) % 3 != 0:
            return Board(self.trocaValores(self.zero, self.zero + 1), self, 'direita', self.depth + 1)
        else:
            return None

    def vizinhos(self):
        vizinho = [self.praCima(), self.praBaixo(), self.esquerda(), self.direita()]
        return list(filter(None, vizinho))

    def __repr__(self):
       return str(self.state[:3]) + '\n' \
               + str(self.state[3:6]) + '\n' \
               + str(self.state[6:]) + ' '  + str(self.depth) + str(self.operator) + '\n'


In [160]:
p = Board(np.array([1,2,5,3,0,5,6,4,8]))
p

[1 2 5]
[3 0 5]
[6 4 8] 0None

In [161]:
print(p.vizinhos())

[[1 2 5]
[3 4 5]
[6 0 8] 1praCima
, [1 2 5]
[3 0 5]
[4 6 8] 1esquerda
, [1 2 5]
[3 0 5]
[6 8 4] 1direita
]


In [164]:
a = np.array([1,2,5,3,4,5,6,0,8])

In [165]:
a.tolist().index(0)

7

In [112]:
p.index([1,2,5,6,4,5,3,0,8])

array([7, 0, 1, 6, 4, 5, 3, 7, 8])

In [113]:
p

[1 2 5]
[3 4 5]
[6 0 8] 

## Busca em largura

## Busca em Profundidade

## Discorra sobre o desempenho dos métodos em questões de:


1.   Consumo de memória
2.   Processamento



## Referência 


[8-puzzle-problem-using-branch-and-bound](https://www.geeksforgeeks.org/8-puzzle-problem-using-branch-and-bound/)

[ state-space-and-uninformed-search ](https://www.ics.uci.edu/~dechter/courses/ics-271/fall-12/lecture-notes/02-state-space-and-uninformed-search.pdf)


### Leituras

[Buscas - Resumido](https://ricardomatsumura.medium.com/algoritmos-de-busca-para-intelig%C3%AAncia-artificial-7cb81172396c)


### Vídeos

[Representação do Conhecimento](https://www.youtube.com/watch?v=V-O-RFSRe-E)

[Busca em Largura](https://www.youtube.com/watch?v=KiCBXu4P-2Y)

[Busca em Profundidade](https://www.youtube.com/watch?v=KiCBXu4P-2Y)
